// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: pb/game_message.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerType int32

const (
	PlayerType_WHITE PlayerType = 0
	PlayerType_BLACK PlayerType = 1
)

// Enum value maps for PlayerType.
var (
	PlayerType_name = map[int32]string{
		0: "WHITE",
		1: "BLACK",
	}
	PlayerType_value = map[string]int32{
		"WHITE": 0,
		"BLACK": 1,
	}
)

func (x PlayerType) Enum() *PlayerType {
	p := new(PlayerType)
	*p = x
	return p
}

func (x PlayerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_game_message_proto_enumTypes[0].Descriptor()
}

func (PlayerType) Type() protoreflect.EnumType {
	return &file_pb_game_message_proto_enumTypes[0]
}

func (x PlayerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerType.Descriptor instead.
func (PlayerType) EnumDescriptor() ([]byte, []int) {
	return file_pb_game_message_proto_rawDescGZIP(), []int{0}
}

// Up message
type Matching struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Matching) Reset() {
	*x = Matching{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_game_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Matching) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Matching) ProtoMessage() {}

func (x *Matching) ProtoReflect() protoreflect.Message {
	mi := &file_pb_game_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Matching.ProtoReflect.Descriptor instead.
func (*Matching) Descriptor() ([]byte, []int) {
	return file_pb_game_message_proto_rawDescGZIP(), []int{0}
}

// Down message
type MatchingConfirm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MatchingConfirm) Reset() {
	*x = MatchingConfirm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_game_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchingConfirm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchingConfirm) ProtoMessage() {}

func (x *MatchingConfirm) ProtoReflect() protoreflect.Message {
	mi := &file_pb_game_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchingConfirm.ProtoReflect.Descriptor instead.
func (*MatchingConfirm) Descriptor() ([]byte, []int) {
	return file_pb_game_message_proto_rawDescGZIP(), []int{1}
}

// Down message
type MatchingError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *MatchingError) Reset() {
	*x = MatchingError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_game_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchingError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchingError) ProtoMessage() {}

func (x *MatchingError) ProtoReflect() protoreflect.Message {
	mi := &file_pb_game_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchingError.ProtoReflect.Descriptor instead.
func (*MatchingError) Descriptor() ([]byte, []int) {
	return file_pb_game_message_proto_rawDescGZIP(), []int{2}
}

func (x *MatchingError) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MatchingError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Down message
type Matched struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player PlayerType `protobuf:"varint,1,opt,name=player,proto3,enum=proto.PlayerType" json:"player,omitempty"`
}

func (x *Matched) Reset() {
	*x = Matched{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_game_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Matched) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Matched) ProtoMessage() {}

func (x *Matched) ProtoReflect() protoreflect.Message {
	mi := &file_pb_game_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Matched.ProtoReflect.Descriptor instead.
func (*Matched) Descriptor() ([]byte, []int) {
	return file_pb_game_message_proto_rawDescGZIP(), []int{3}
}

func (x *Matched) GetPlayer() PlayerType {
	if x != nil {
		return x.Player
	}
	return PlayerType_WHITE
}

// Up message
type MatchedConfirm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player PlayerType `protobuf:"varint,1,opt,name=player,proto3,enum=proto.PlayerType" json:"player,omitempty"`
}

func (x *MatchedConfirm) Reset() {
	*x = MatchedConfirm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_game_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchedConfirm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchedConfirm) ProtoMessage() {}

func (x *MatchedConfirm) ProtoReflect() protoreflect.Message {
	mi := &file_pb_game_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchedConfirm.ProtoReflect.Descriptor instead.
func (*MatchedConfirm) Descriptor() ([]byte, []int) {
	return file_pb_game_message_proto_rawDescGZIP(), []int{4}
}

func (x *MatchedConfirm) GetPlayer() PlayerType {
	if x != nil {
		return x.Player
	}
	return PlayerType_WHITE
}

// Up message
type DropDot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X      int32      `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y      int32      `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Player PlayerType `protobuf:"varint,3,opt,name=player,proto3,enum=proto.PlayerType" json:"player,omitempty"`
}

func (x *DropDot) Reset() {
	*x = DropDot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_game_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DropDot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropDot) ProtoMessage() {}

func (x *DropDot) ProtoReflect() protoreflect.Message {
	mi := &file_pb_game_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropDot.ProtoReflect.Descriptor instead.
func (*DropDot) Descriptor() ([]byte, []int) {
	return file_pb_game_message_proto_rawDescGZIP(), []int{5}
}

func (x *DropDot) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *DropDot) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *DropDot) GetPlayer() PlayerType {
	if x != nil {
		return x.Player
	}
	return PlayerType_WHITE
}

// Down message
type DropDotConfirm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X      int32      `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y      int32      `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Player PlayerType `protobuf:"varint,3,opt,name=player,proto3,enum=proto.PlayerType" json:"player,omitempty"`
}

func (x *DropDotConfirm) Reset() {
	*x = DropDotConfirm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_game_message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DropDotConfirm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropDotConfirm) ProtoMessage() {}

func (x *DropDotConfirm) ProtoReflect() protoreflect.Message {
	mi := &file_pb_game_message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropDotConfirm.ProtoReflect.Descriptor instead.
func (*DropDotConfirm) Descriptor() ([]byte, []int) {
	return file_pb_game_message_proto_rawDescGZIP(), []int{6}
}

func (x *DropDotConfirm) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *DropDotConfirm) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *DropDotConfirm) GetPlayer() PlayerType {
	if x != nil {
		return x.Player
	}
	return PlayerType_WHITE
}

// Up message
type DropCheck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player PlayerType `protobuf:"varint,1,opt,name=player,proto3,enum=proto.PlayerType" json:"player,omitempty"`
}

func (x *DropCheck) Reset() {
	*x = DropCheck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_game_message_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DropCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropCheck) ProtoMessage() {}

func (x *DropCheck) ProtoReflect() protoreflect.Message {
	mi := &file_pb_game_message_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropCheck.ProtoReflect.Descriptor instead.
func (*DropCheck) Descriptor() ([]byte, []int) {
	return file_pb_game_message_proto_rawDescGZIP(), []int{7}
}

func (x *DropCheck) GetPlayer() PlayerType {
	if x != nil {
		return x.Player
	}
	return PlayerType_WHITE
}

// Down message
type DropCheckConfirm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player PlayerType `protobuf:"varint,1,opt,name=player,proto3,enum=proto.PlayerType" json:"player,omitempty"`
}

func (x *DropCheckConfirm) Reset() {
	*x = DropCheckConfirm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_game_message_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DropCheckConfirm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropCheckConfirm) ProtoMessage() {}

func (x *DropCheckConfirm) ProtoReflect() protoreflect.Message {
	mi := &file_pb_game_message_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropCheckConfirm.ProtoReflect.Descriptor instead.
func (*DropCheckConfirm) Descriptor() ([]byte, []int) {
	return file_pb_game_message_proto_rawDescGZIP(), []int{8}
}

func (x *DropCheckConfirm) GetPlayer() PlayerType {
	if x != nil {
		return x.Player
	}
	return PlayerType_WHITE
}

// Down message
type Win struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player PlayerType `protobuf:"varint,1,opt,name=player,proto3,enum=proto.PlayerType" json:"player,omitempty"`
}

func (x *Win) Reset() {
	*x = Win{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_game_message_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Win) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Win) ProtoMessage() {}

func (x *Win) ProtoReflect() protoreflect.Message {
	mi := &file_pb_game_message_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Win.ProtoReflect.Descriptor instead.
func (*Win) Descriptor() ([]byte, []int) {
	return file_pb_game_message_proto_rawDescGZIP(), []int{9}
}

func (x *Win) GetPlayer() PlayerType {
	if x != nil {
		return x.Player
	}
	return PlayerType_WHITE
}

// Up message
// Down message
type Surrender struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player PlayerType `protobuf:"varint,1,opt,name=player,proto3,enum=proto.PlayerType" json:"player,omitempty"`
}

func (x *Surrender) Reset() {
	*x = Surrender{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_game_message_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Surrender) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Surrender) ProtoMessage() {}

func (x *Surrender) ProtoReflect() protoreflect.Message {
	mi := &file_pb_game_message_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Surrender.ProtoReflect.Descriptor instead.
func (*Surrender) Descriptor() ([]byte, []int) {
	return file_pb_game_message_proto_rawDescGZIP(), []int{10}
}

func (x *Surrender) GetPlayer() PlayerType {
	if x != nil {
		return x.Player
	}
	return PlayerType_WHITE
}

var File_pb_game_message_proto protoreflect.FileDescriptor

var file_pb_game_message_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x62, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0a,
	0x0a, 0x08, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x22, 0x11, 0x0a, 0x0f, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x22, 0x3d, 0x0a,
	0x0d, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x34, 0x0a, 0x07,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x64, 0x12, 0x29, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x22, 0x3b, 0x0a, 0x0e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x64, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x12, 0x29, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22,
	0x50, 0x0a, 0x07, 0x44, 0x72, 0x6f, 0x70, 0x44, 0x6f, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x12, 0x29, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x22, 0x57, 0x0a, 0x0e, 0x44, 0x72, 0x6f, 0x70, 0x44, 0x6f, 0x74, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x72, 0x6d, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01,
	0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x12,
	0x29, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x36, 0x0a, 0x09, 0x44, 0x72,
	0x6f, 0x70, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x29, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x22, 0x3d, 0x0a, 0x10, 0x44, 0x72, 0x6f, 0x70, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x12, 0x29, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x22, 0x30, 0x0a, 0x03, 0x57, 0x69, 0x6e, 0x12, 0x29, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x22, 0x36, 0x0a, 0x09, 0x53, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x12, 0x29, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2a, 0x22, 0x0a, 0x0a, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x57, 0x48, 0x49,
	0x54, 0x45, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x4c, 0x41, 0x43, 0x4b, 0x10, 0x01, 0x42,
	0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_game_message_proto_rawDescOnce sync.Once
	file_pb_game_message_proto_rawDescData = file_pb_game_message_proto_rawDesc
)

func file_pb_game_message_proto_rawDescGZIP() []byte {
	file_pb_game_message_proto_rawDescOnce.Do(func() {
		file_pb_game_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_game_message_proto_rawDescData)
	})
	return file_pb_game_message_proto_rawDescData
}

var file_pb_game_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_game_message_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pb_game_message_proto_goTypes = []interface{}{
	(PlayerType)(0),          // 0: proto.PlayerType
	(*Matching)(nil),         // 1: proto.Matching
	(*MatchingConfirm)(nil),  // 2: proto.MatchingConfirm
	(*MatchingError)(nil),    // 3: proto.MatchingError
	(*Matched)(nil),          // 4: proto.Matched
	(*MatchedConfirm)(nil),   // 5: proto.MatchedConfirm
	(*DropDot)(nil),          // 6: proto.DropDot
	(*DropDotConfirm)(nil),   // 7: proto.DropDotConfirm
	(*DropCheck)(nil),        // 8: proto.DropCheck
	(*DropCheckConfirm)(nil), // 9: proto.DropCheckConfirm
	(*Win)(nil),              // 10: proto.Win
	(*Surrender)(nil),        // 11: proto.Surrender
}
var file_pb_game_message_proto_depIdxs = []int32{
	0, // 0: proto.Matched.player:type_name -> proto.PlayerType
	0, // 1: proto.MatchedConfirm.player:type_name -> proto.PlayerType
	0, // 2: proto.DropDot.player:type_name -> proto.PlayerType
	0, // 3: proto.DropDotConfirm.player:type_name -> proto.PlayerType
	0, // 4: proto.DropCheck.player:type_name -> proto.PlayerType
	0, // 5: proto.DropCheckConfirm.player:type_name -> proto.PlayerType
	0, // 6: proto.Win.player:type_name -> proto.PlayerType
	0, // 7: proto.Surrender.player:type_name -> proto.PlayerType
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_pb_game_message_proto_init() }
func file_pb_game_message_proto_init() {
	if File_pb_game_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_game_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Matching); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_game_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchingConfirm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_game_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchingError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_game_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Matched); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_game_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchedConfirm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_game_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DropDot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_game_message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DropDotConfirm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_game_message_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DropCheck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_game_message_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DropCheckConfirm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_game_message_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Win); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_game_message_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Surrender); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_game_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_game_message_proto_goTypes,
		DependencyIndexes: file_pb_game_message_proto_depIdxs,
		EnumInfos:         file_pb_game_message_proto_enumTypes,
		MessageInfos:      file_pb_game_message_proto_msgTypes,
	}.Build()
	File_pb_game_message_proto = out.File
	file_pb_game_message_proto_rawDesc = nil
	file_pb_game_message_proto_goTypes = nil
	file_pb_game_message_proto_depIdxs = nil
}
